FROM ruby:2.7.0

RUN mkdir /app

WORKDIR /app

ADD Gemfile /app/
ADD Gemfile.lock /app/

RUN bundle config set path 'vendor/bundle'
RUN bundle install -j4

ADD . /app

EXPOSE 80

CMD ["bundle", "exec", "puma"]
