FROM ruby:2.7.0

WORKDIR /app

ADD Gemfile /app/
ADD Gemfile.lock /app/

RUN bundle config set path 'vendor/bundle'
RUN bundle install -j4

ADD ./ /app

VOLUME /app/public
VOLUME /app/tmp
VOLUME /app/log

EXPOSE 4000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
