AWSTemplateFormatVersion: '2010-09-09'
Description: deploy service
Resources:
  # Service 定義
  TodoAppService:
    Type: AWS::ECS::Service
    Properties: 
      # CapacityProviderStrategy: 
      #   - CapacityProviderStrategyItem
      Cluster: !ImportValue TodoAppClusterName
      # DeploymentConfiguration:
      #   DeploymentConfiguration
      # DeploymentController: 
      #   DeploymentController
      # DesiredCount: Integer
      # EnableECSManagedTags: Boolean
      # HealthCheckGracePeriodSeconds: Integer
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: todo-app-frontend-production-container
          # タスク定義時に行ったコンテナポートを指定する必要がある
          ContainerPort: 3000
          # LoadBalancerNameはClassicLoadBalancerのときのみ
          # LoadBalancerName: String
          # ALB, NLBはここで指定する
          TargetGroupArn: !ImportValue TodoAppTargetGroupARN
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !ImportValue TodoAppSecurityGroupID
          Subnets: 
            - !ImportValue TodoAppPublicSubnet1AID
      # PlacementConstraints: 
      #   - PlacementConstraint
      # PlacementStrategies: 
      #   - PlacementStrategy
      # PlatformVersion: String
      # PropagateTags: String
      # Role: String
      # SchedulingStrategy: String
      # ServiceArn: String
      ServiceName: todo-app-production-service
      # ServiceRegistries: 
      #   - ServiceRegistry
      # Tags:
      #   - Tag
      TaskDefinition: !ImportValue TodoAppTaskDefinition