AWSTemplateFormatVersion: '2010-09-09'
Description: deploy service
Resources:
  # Service Discoverty(CloudMap)参考: https://aws.amazon.com/jp/premiumsupport/knowledge-center/cloudformation-ecs-service-discovery/
  # Private NameSpaceの作成→ECS Service DiscovertyはCloudMap APIを統合している。CloudMap APIを使用してPrivate Hosted Zoneを作成する。
  TodoAppPrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
        Name: kawada.work
        Vpc: !ImportValue TodoAppVPCID

  # Discovery Serviceの作成→作成したPrivate Hosted Zoneに対してDNSレコードの設定を行う。
  TodoAppDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the Demo Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: backend
      NamespaceId: !Ref TodoAppPrivateNamespace

  # Frontend Service 定義
  TodoAppFrontendService:
    Type: AWS::ECS::Service
    Properties: 
      # CapacityProviderStrategy: 
      #   - CapacityProviderStrategyItem
      Cluster: !ImportValue TodoAppClusterName
      # DeploymentConfiguration:
      #   DeploymentConfiguration
      # DeploymentController: 
      #   DeploymentController
      # DesiredCount: Integer
      # EnableECSManagedTags: Boolean
      # HealthCheckGracePeriodSeconds: Integer
      LaunchType: FARGATE
      LoadBalancers: 
        - ContainerName: todo-app-frontend-production-container
          # タスク定義時に行ったコンテナポートを指定する必要がある
          ContainerPort: 3000
          # LoadBalancerNameはClassicLoadBalancerのときのみ
          # LoadBalancerName: String
          # ALB, NLBはここで指定する
          TargetGroupArn: !ImportValue TodoAppTargetGroupARN
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !ImportValue TodoAppFrontendSecurityGroupID
          Subnets: 
            - !ImportValue TodoAppPublicSubnet1AID
      # PlacementConstraints: 
      #   - PlacementConstraint
      # PlacementStrategies: 
      #   - PlacementStrategy
      # PlatformVersion: String
      # PropagateTags: String
      # Role: String
      # SchedulingStrategy: String
      # ServiceArn: String
      ServiceName: frontend
      # ServiceRegistries: 
      #   - ServiceRegistry
      # Tags:
      #   - Tag
      TaskDefinition: !ImportValue TodoAppFrontendTaskDefinitionARN

  # Backend Service 定義
  TodoAppBackendService:
    Type: AWS::ECS::Service
    Properties: 
      # CapacityProviderStrategy: 
      #   - CapacityProviderStrategyItem
      Cluster: !ImportValue TodoAppClusterName
      # DeploymentConfiguration:
      #   DeploymentConfiguration
      # DeploymentController: 
      #   DeploymentController
      # DesiredCount: Integer
      # EnableECSManagedTags: Boolean
      # HealthCheckGracePeriodSeconds: Integer
      LaunchType: FARGATE
      # LoadBalancers: 
      #   - LoadBalancer
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !ImportValue TodoAppBackendSecurityGroupID
          Subnets: 
            - !ImportValue TodoAppPrivateSubnet1AID
      # PlacementConstraints: 
      #   - PlacementConstraint
      # PlacementStrategies: 
      #   - PlacementStrategy
      # PlatformVersion: String
      # PropagateTags: String
      # Role: String
      # SchedulingStrategy: String
      # ServiceArn: String
      # ここで命名したサービス名がサブドメインとなる
      ServiceName: backend
      ServiceRegistries: 
        - # ContainerName: String
          # ContainerPort: Integer
          Port: 80
          RegistryArn: !GetAtt TodoAppDiscoveryService.Arn
      # Tags: 
      #   - Tag
      TaskDefinition: !ImportValue TodoAppBackendTaskDefinitionARN